// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    title: "varchar(255)"
  };

}).call(this);
